version: '3.3'

services:
  postgresql:
    image: postgres:13.3
    container_name: admin-db
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@%!)(^
      - POSTGRES_DB=postgres
    volumes:
      - /var/lib/docker/data/database:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: admin-storage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=1jan@%!)(^
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=BELETNEWS
    volumes:
      - /var/lib/docker/data/storage:/data
    command: server /data

  admin_panel_backend:
    build: ./admin-panel-backend/
    container_name: backend
    restart: on-failure
    ports:
      - 7778:7778

  admin_panel_frontend:
    build: ./admin-panel-frontend/
    container_name: frontend
    restart: on-failure
    ports:
      - 8087:80
    depends_on: 
      - admin_panel_backend

networks:
  default:
    driver: bridge