version: '3.3'

services:
  admin_panel_backend:
    build: ./admin-panel-backend/
    container_name: backend
    restart: on-failure
    ports:
      - 7778:7778

  admin_panel_frontend:
    build: ./admin-panel-frontend/
    container_name: frontend
    restart: on-failure
    ports:
      - 8087:80
    depends_on: 
      - admin_panel_backend

networks:
  default:
    driver: bridge