server:  
  ip: "backend"
  port: "7770"
  protocol: "http"

db:
  host: "db"
  port: 5470
  dbname: "postgres"
  username: "postgres"
  password: "@%!)(^"
  sslmode: "disable"

storage:
  host: "storage"
  port: "9070"
  username: "admin"
  password: "1jan@%!)(^"
  sslmode: false
