server:  
  ip: "144.91.104.118"
  port: "7770"
  protocol: "http"

db:
  host: "db"
  port: 5432
  dbname: "postgres"
  username: "postgres"
  password: "@%!)(^"
  sslmode: "disable"

storage:
  host: "storage"
  port: "9000"
  username: "admin"
  password: "1jan@%!)(^"
  sslmode: false
