server:  
  ip: "backend"
  port: "7778"
  protocol: "http"

db:
  host: "admin-db"
  port: 5432
  dbname: "postgres"
  username: "postgres"
  password: "@%!)(^"
  sslmode: "disable"

storage:
  host: "admin-storage"
  port: "9000"
  username: "admin"
  password: "1jan@%!)(^"
  sslmode: false
